[firebase]
type = "service_account"
project_id = "rag-based-assistant-4fc06"
private_key_id = "0a5ef0361c7ada2ac22c29c4339adf9bfbb99a19"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCk4niQSStV3oQE
eXWgHoTgkgscsrmW9raz1k2PoRnpKtsXBL2HbvOdA405hQYDx/8Y22HgJ5DfSbjV
KowyWAYKZh+CT5av+04n24tnp4RLv0OS0CVIOw9M7umrRiQEJYODUBppU7IlK5Hg
WnLrbQZboqraVJDr566Hf0diEia5tuQRLGjKV4lhf9zteQJ37xbkWvIbh353Z9lJ
YnNiXP6GXjAP908Ibglxlu18N+6Wn3KRJnBBmKS0p/kVKZKhFySDeiolBLMAIhKw
Qr9cVELCUKrg0WXimdwiCTIcmPHehcL3ZpPW5nsRWTsrvjnzl9Z7dx0OX2CpLGJK
DdwJUn8bAgMBAAECggEACOOcEVdIf/lzj5QxZwpOKpc6Wc05hoMoKBDadJmq/nA3
iImnuB30rJcs7W1s/MDdpqw+c2mz/JMKZRTv+E+DioWlQY64i9CWDuhd9HQfrz+7
97XDVMi4/fJMDwDvNHlbROCJfqUq+lMGKxy6i6kAienT9oT5nSY2jrUqFtuYp963
K2vAWCO21/ybJNlc9G9s4cWbS41b18wq/rn6chmbdgNZPMVNTrqoOYhu1ussBNQg
1945IL0dpBeg87G+qnBzPCeWPqXCWi03itHO/V3lyTpSKFVa3SuBxwOhckRM7vKs
EVdZ3Y1Q2GxEgnvhs/qRd0MY5sEqtB4q8ilGfcd1NQKBgQDlA3HB8M+KVP59QdvA
i8FSiD9B+Y1hC/BRzgtbKVODU9w+FmgGZxY6IbQpdSyUmY3cS8AWT+oIzs8mTKDi
l4o3syvXAyyz4ChSC3ILjdy70ehjeSPnCwNsphq21Qlg0aYgtu812PTpmzoV5oyd
NeZDmSnhDdRpGX7fnNPAdwFTDQKBgQC4UHqnVzblEh/Wj+98Q7PZNoES18VKMtFB
1bggDfIlWiF84HyrOpctF8f6bcMnROX9+vuAuRaReSSfGT9+KXic05RTI63Tum9q
7Ohu/Am4fXW3PfpuAZ8iURF7FOh3zjD2/Qof1/aisE7ToU4+O1+eIINMjpm3BLEd
14/GsnqwxwKBgGbhCjyGsqVBE2YvrMmtvrYV0N0Rf2qmU1pchot4YDTx+lHF/QtL
ShfpRicNpW5IIQti2DLtyYQVa8eXyvqf+w6UpdAcc/uGanaY/62jGBMj9BKju/Yx
42Lup7eUsnbVF51AsOtuwG8lNY3bGTYSnZOmfcLFVLO2KWHI8PNYQrcNAoGARKtv
VyNuR2A+TnFn93M98YKWClArqB5Qymd25zJq8jGnYmA88oqswlcm4Y29dMb9rWey
Bl5vIxnwY/pDJp0K29sUWvljDQxb8Il9e8QZVwwfLHtB73RZNq7fhWzfw6sloQ/b
ksuijzCC3eQuQ49Za4+Pe5lxebecyZKDdbMPdQcCgYArGSvQpEH0zRydG+Ntk/P1
54CzvY8lKLb0j3WCopyAeMFluMAaLWTzsfE1tENJv2VVNQ9dKzBbTVd3YNzrDkr2
K0rU88U5eplqpGPKC+ywhE+Ewg4MTIRVWGeOf99gXZ9uD5qyJqlxh9Ttfv2K2m2U
yBeCSRdENMlRyTzP1079wg==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@rag-based-assistant-4fc06.iam.gserviceaccount.com"
client_id = "104507370558284558703"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@rag-based-assistant-4fc06.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
